### ISSUE TITLE
Create presentation

### ISSUE THREAD

**Issue by LoreVanSantvliet** [IBP-21-22/intbioproj#17]
- [x] Vassili's part
- [x] Lore's part
- [x] Darina's part
- [x] Adriana's part
- [x] Practice presentation (Lore)

**Comment by DadaAb** [comment]
[Presentation link.](https://kuleuven-my.sharepoint.com/:p:/g/personal/darina_abaffyova_student_kuleuven_be/EdKcflmytilCuNLbWPZQZeEBYPtxxTmEVHG9CEDbnmQQRg?e=hVX6UP)
