### ISSUE TITLE
Presentation + Meeting with Raúl&Lloyd 211021

### ISSUE THREAD

**Issue by adriana-madi** [IBP-21-22/intbioproj#6]
Hey everybody! 
I'm opening this issue so that people can drop their notes/findings/links etc.. in here.
We will also share the link to the presentation here or upload the relevant slides to be merged.

This can also be used as a thread for communicating any thoughts/concerns/new epiphanies with regards to the presentation for Thursday. 

I will also update it with notes that I take during the meeting itself. 

Good Luck and most importantly, HAVE FUN!

**Comment by adriana-madi** [comment]
_I'll Start:_

**Interesting Links:**
Comparison between: UMAP, PCA, LDA, T-SNE (with some code/example)
https://towardsdatascience.com/dimensionality-reduction-for-data-visualization-pca-vs-tsne-vs-umap-be4aa7b1cb29

Tutorial on T-SNE (includes cool visual, code):
https://www.oreilly.com/content/an-illustrated-introduction-to-the-t-sne-algorithm/

More info on UMAP:
https://arxiv.org/abs/1802.03426

**Comment by adriana-madi** [comment]
I've created a small presentation (filled only my slide though, the question slide, and the future planning slide).
Feel free to add your slide information within. Don't think it is required for us to make them super fancy, would just be nice to have some visuals while discussing (and also to remember what points we want to make so that we don't forget and also stay on track)

Let me know what you think :) (I made it in keynote and exported it to powerpoint..let me know if there are any issues)
[211021Meeting.pptx](https://github.com/VasLem/intbioproj/files/7385040/211021Meeting.pptx)

**Comment by VasLem** [comment]
This is the updated link:
https://kuleuven-my.sharepoint.com/:p:/g/personal/vasileios_lemonidis_student_kuleuven_be/EaAne-7ajn1LnTvdME1T-wsBQZsDtK4JWZGWjNcA8oXG6Q?e=Jr7qz1

**Comment by DadaAb** [comment]
Meeting notes:

![image](https://user-images.githubusercontent.com/37106086/138253289-b531b7ba-ff60-4998-be5f-0f79a244e581.png)
